//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoapClient.DataService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://soap/", ConfigurationName="DataService.SOAPInterface")]
    public interface SOAPInterface {
        
        // CODEGEN: Parametr „return” wymaga dodatkowych informacji o schemacie, których nie można uzyskać w trybie parametru. Określony atrybut to „System.Xml.Serialization.XmlArrayAttribute”.
        [System.ServiceModel.OperationContractAttribute(Action="http://soap/SOAPInterface/getDataRequest", ReplyAction="http://soap/SOAPInterface/getDataResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoapClient.DataService.getDataResponse getData(SoapClient.DataService.getDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://soap/SOAPInterface/getDataRequest", ReplyAction="http://soap/SOAPInterface/getDataResponse")]
        System.Threading.Tasks.Task<SoapClient.DataService.getDataResponse> getDataAsync(SoapClient.DataService.getDataRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getData", WrapperNamespace="http://soap/", IsWrapped=true)]
    public partial class getDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string arg0;
        
        public getDataRequest() {
        }
        
        public getDataRequest(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getDataResponse", WrapperNamespace="http://soap/", IsWrapped=true)]
    public partial class getDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute()]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Nullable<int>[] @return;
        
        public getDataResponse() {
        }
        
        public getDataResponse(System.Nullable<int>[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SOAPInterfaceChannel : SoapClient.DataService.SOAPInterface, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SOAPInterfaceClient : System.ServiceModel.ClientBase<SoapClient.DataService.SOAPInterface>, SoapClient.DataService.SOAPInterface {
        
        public SOAPInterfaceClient() {
        }
        
        public SOAPInterfaceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SOAPInterfaceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SOAPInterfaceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SOAPInterfaceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoapClient.DataService.getDataResponse SoapClient.DataService.SOAPInterface.getData(SoapClient.DataService.getDataRequest request) {
            return base.Channel.getData(request);
        }
        
        public System.Nullable<int>[] getData(string arg0) {
            SoapClient.DataService.getDataRequest inValue = new SoapClient.DataService.getDataRequest();
            inValue.arg0 = arg0;
            SoapClient.DataService.getDataResponse retVal = ((SoapClient.DataService.SOAPInterface)(this)).getData(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoapClient.DataService.getDataResponse> SoapClient.DataService.SOAPInterface.getDataAsync(SoapClient.DataService.getDataRequest request) {
            return base.Channel.getDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoapClient.DataService.getDataResponse> getDataAsync(string arg0) {
            SoapClient.DataService.getDataRequest inValue = new SoapClient.DataService.getDataRequest();
            inValue.arg0 = arg0;
            return ((SoapClient.DataService.SOAPInterface)(this)).getDataAsync(inValue);
        }
    }
}
